### ISSUE TITLE
Missing "maintainer" and "license" sections in README.md file

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/hax#4]
Maintainers for Backdrop projects are determined by the names that are listed in the "Maintainers" section in the readme file, but this project is missing that section. 

@btopro I am assuming that you are the maintainer for the project, could you please add your name? Please see [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md) of what a README.md file usually contains for Backdrop projects. 

Thank you!

**Comment by btopro** [comment]
Should be good to go in the PR; is this why I lost write access to this space?

**Comment by jenlampton** [comment]
> is this why I lost write access to this space?

No, that was unrelated (sorry about that too!) but we are hoping to automate access based on the README 🤞

**Comment by jenlampton** [comment]
Your access should be restored now.
